<?php
   /**
 	* @category   Php4u
	* @package    Php4u_BlastLuceneSearch
	* @author     Marcin Szterling <marcin@php4u.co.uk>
	* @copyright  Php4u Marcin Szterling (c) 2013
	* @license http://php4u.co.uk/licence/
	* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	* THE SOFTWARE.
	* Any form of distribution, sell, transfer forbidden see licence above
	*/
?>
<div class="table-left">
<div class="top">Last 10 searches</div>
<div class="term">search term</div>
<div class="result">results</div>
<div class="number">Number of Uses</div>

<?php echo $this->getTableDataHtml(); ?>

<div class="select-bg"><h4>select period</h4> 
<select name="table3period" id="table3period" class="today">
<?php echo $this->getSelectOptionsHtml($this->getPeriod()); ?>
</select></div>
</div>
