
<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Product Returns')?></h3></td>
            <td align="right"><button type="button" class="scalable" onclick="setLocation('<?php echo $this->getUrl('adminhtml/ProductReturn_Admin/GridOrder/'); ?>')" style=""><span><?php echo $this->__('Create New Product Return'); ?></span></button></td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>

</div>