<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper = $this->helper('catalogsearch');
?>

<div class="search panel panel--from-bottom">
    <div class="panel__inner">

        <div class="panel__header">
            <h2 class="panel__title"><span class="panel__title-text"><?php echo $this->__('Search') ?></span></h2>
            <button class="panel__close panel__action"><svg class="panel__action-icon panel__action-icon--close svg-icon"><use xlink:href="#icon-close" /></svg><span class="hide"><?php echo $this->__("Close") ?></span></button>
        </div><!-- .panel__header -->

        <div class="panel__content">
            <div class="panel__container">

                <form class="search__form form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">

                    <p class="form__field">
                        <input class="search__textfield textfield" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" placeholder="<?php echo $this->__('Search our entire inventory of supplements...')?>" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>">
                        <!-- <span class="search-autocomplete-indicator" style="display:none;"></span> -->
                        <!-- <span class="search-autocomplete-close" style="display:none;"></span> -->
                    </p>

                    <p class="form__field">
                        <button class="search__submit button" type="submit"><?php echo $this->__('Search') ?></button>
                    </p>

                    <!-- <div class="search-autocomplete-container" style="display:none;">
                        <div class="search-autocomplete-arrow"></div>
                        <div class="search-autocomplete"></div>
                    </div> -->

                </form>

            </div><!-- .panel__container -->
        </div><!-- .panel__content -->

    </div><!-- .panel__inner -->
</div><!-- .panel -->
