<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><ul class="list-group">

    <?php $first = true ?>
    <?php foreach ($this->getItems() as $_item): ?>
        <?php if ($first): ?>
            <li class="list-group__item list-group__item--without-border">
                <a class="list-group__item-title filter__clear js-clear-current-filter" data-filter-name="<?php echo $_item->getFilter()->getRequestVar() ?>" data-filter-title="<?php echo $this->getName() ?>">
                    <svg class="filter__clear-icon svg-icon"><use xlink:href="#icon-clear-filter" /></svg><?php echo $this->__('Clear this filter') ?>
                </a>
            </li>

            <?php $first = false ?>
        <?php endif ?>

        <li class="list-group__item filter__parameter js-filter-option-click" data-filter-title="<?php echo $this->getName() ?>">
            <span class="radio">
                <input class="radio__self" type="radio" name="<?php echo $_item->getFilter()->getRequestVar() ?>" id="filter-<?php echo $_item->getFilter()->getRequestVar() ?>-<?php echo $_item->getValue() ?>" value="<?php echo $_item->getValue() ?>">
                <label class="list-group__item-title radio__label" for="filter-<?php echo $_item->getFilter()->getRequestVar() ?>-<?php echo $_item->getValue() ?>">
                    <span class="list-group__icon list-group__icon--radio radio__icon-wrapper">
                        <svg class="radio__icon radio__icon--unchecked svg-icon"><use xlink:href="#icon-radio" /></svg>
                        <svg class="radio__icon radio__icon--checked svg-icon"><use xlink:href="#icon-radio--checked" /></svg>
                    </span>
                    <span class="radio__text filter__option-text"><?php echo $_item->getLabel() ?></span>
                </label>
            </span>
        </li>
    <?php endforeach ?>

</ul>
