<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_filters = $this->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <li class="list-group__item list-group__item--without-border">
        <a class="list-group__item-title filter__clear js-clear-all-filters">
            <svg class="filter__clear-icon svg-icon"><use xlink:href="#icon-clear-filter" /></svg><?php echo $this->__('Clear all filters') ?>
        </a>
    </li>

    <?php foreach ($_filters as $_filter): ?>
        <li class="list-group__item filter__parameter">
            <span class="list-group__item-title js-remove-applied-filter" data-filter-name="<?php echo $_filter->getFilter()->getRequestVar() ?>">
                <?php echo $_filter->getName() ?>

                <span class="filter__selected-option"><?php echo $this->__('Filter By') ?>: <?php echo $_filter->getLabel() ?></span>

                <span class="filter__parameter-clear list-group__icon"><?php echo $this->__('Clear') ?></span>
            </span>
        </li>
    <?php endforeach; ?>
<?php endif; ?>
