<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($crumbs && is_array($crumbs)): ?>

    <?php foreach($crumbs as $_crumbInfo): ?>
        <?php if (!$_crumbInfo['last']): ?>
            <?php $firstLink = $_crumbInfo; ?>
        <?php else: ?>
                <?php $lastLink = $_crumbInfo; ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (!Mage::registry('is_home_page_flag')): ?>
        <a class="page-header__action page-header__action--back" href="<?php echo $firstLink['link'] ?>" title="<?php echo $this->htmlEscape($firstLink['title']) ?>">
            <svg class="page-header__action-icon svg-icon"><use xlink:href="#icon-page-back" /></svg><?php /* echo $this->htmlEscape($firstLink['label']) */ ?>
        </a>
    <?php endif; ?>

    <h1 class="page-header__title">
        <?php echo $this->htmlEscape($lastLink['label']) ?>
    </h1>

<?php else: ?>

    <?php $headBlock = $this->getLayout()->getBlock('head'); ?>

    <?php if(!Mage::registry('is_home_page_flag')): ?>
        <a class="page-header__action page-header__action--back" href="<?php echo Mage::getUrl('') ?>" title="<?php echo $this->__('Home') ?>">
            <svg class="page-header__action-icon svg-icon"><use xlink:href="#icon-page-back" /></svg>
        </a>
    <?php endif; ?>

    <h1 class="page-header__title">
        <?php echo $headBlock ? $this->htmlEscape($headBlock->getTitle()) : '' ?>
    </h1>

<?php endif; ?>
