<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Mage_Page_Block_Html_CookieNotice
 */
?>
<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="cookie-notice">
            <div class="cookie-notice__content">
                <p>
                    <strong><?php echo $this->__('JavaScript seems to be disabled in your browser.'); ?></strong><br>
                    <?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>

<?php if (@class_exists('Mage_Core_Helper_Cookie') && Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <div class="cookie-notice" id="cookie-notice" style="display: none;">
        <div class="cookie-notice__content">
            <p><?php echo $this->__('This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href="%s">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.', $this->getPrivacyPolicyLink()) ?></p>
        </div>

        <p class="cookie-notice__action">
            <button class="button" onclick="allowSaveCookie()"><?php echo $this->__('Allow') ?></button>
        </p>
    </div>

    <script>
        function allowSaveCookie() {
            Mage.Cookies.set('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>', '<?php echo Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds() ?>', new Date(new Date().getTime() + <?php echo Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));

            if (Mage.Cookies.get('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>')) {
                window.location.reload();
            } else {
                window.location.href = '<?php echo Mage::getUrl('cms/index/noCookies') ?>';
            }
        }

        $('cookie-notice').show();
    </script>
<?php endif; ?>
