<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><meta http-equiv="Content-Type" content="<?php echo $this->getContentType(); ?>">

<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>

<meta content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">

<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>">
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>">
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>">

<link rel="apple-touch-icon-precomposed" href="<?php echo Mage::helper('aw_mobile3/config')->getBookmarksSrc() ? Mage::helper('aw_mobile3/config')->getBookmarksSrc() : $this->getSkinUrl('favicon.ico')?>">
<link rel="shortcut icon" href="<?php echo Mage::helper('aw_mobile3/config')->getBookmarksSrc() ? Mage::helper('aw_mobile3/config')->getBookmarksSrc() : $this->getSkinUrl('favicon.ico')?>">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="<?php echo htmlspecialchars(Mage::app()->getStore()->getFrontendName());?>">

<?php echo $this->getCssJsHtml() ?>


<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,400italic,700italic&subset=latin<?php echo Mage::helper('aw_mobile3/config')->isCyrillicFonts() ? ',cyrillic':''?>">

<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
