<?php if ($this->canShowPopup() === true ): ?>
<script type="text/javascript">
    //<![CDATA[
    var messagePopupClosed = false;
    function openMessagePopup() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        $('message-popup-window').addClassName('show');
    }

    function closeMessagePopup() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
        var request = new Ajax.Request('<?php echo $this->getUrl('adminhtml/MyBms_Popup/closeAjax')?>',
            {
                method:'post'
            });
    }

    Event.observe(window, 'load', openMessagePopup);
    Event.observe(window, 'keyup', function(evt) {
        if(messagePopupClosed) return;
        var code;
        if (evt.keyCode) code = evt.keyCode;
        else if (evt.which) code = evt.which;
        if (code == Event.KEY_ESC) {
            closeMessagePopup();
        }
    });
    //]]>
</script>
<div id="message-popup-window-mask" style="display:none;"></div>
<div id="message-popup-window" class="message-popup">
    <div class="message-popup-head">
        <a href="#" onclick="closeMessagePopup(); return false;" title="helppopup"><span>Close</span></a>
        <h2><?php echo $this->__('Get help from BoostMyShop.com'); ?></h2>
    </div>
    <div class="message-popup-content">
        <div class="message">
            <img src="<?php echo $this->getSkinUrl('images/logo_bms.png'); ?>" alt="logobms" width="52" height="52">
            <p class="message-text"><?php echo $this->__('New HELP button available on each Boost My Shop module pages'); ?></p>
        </div>
    </div>
</div>
<?php endif; ?>