<div class="entry-edit">

    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo $this->__('Smart Report - Dashboard')?></h3></td>
            </tr>
        </table>
    </div>

    <?php foreach($this->getReports() as $report): ?>
        <h2><?php echo $report->getName(); ?></h2>
        <?php echo $this->renderReport($report); ?>
    <?php endforeach; ?>
</div>