<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="address-book address-book__wrapper">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="address-book__section">
        <h2 class="address-book__section-title"><?php echo $this->__('Default Addresses') ?></h2>
        <div class="address-book__address-block">
            <h3 class="address-book__address-title"><?php echo $this->__('Default Billing Address') ?></h3>
            <address class="address-book__address">
                <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                    <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                    <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
                <?php else: ?>
                    <p><?php echo $this->__('You have no default billing address in your address book.') ?></p>
                <?php endif ?>
            </address>
        </div><!-- .address-book__address-block -->
        <div class="address-book__address-block">
            <h3 class="address-book__address-title"><?php echo $this->__('Default Shipping Address') ?></h3>
            <address class="address-book__address">
                <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                    <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                    <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
                <?php else: ?>
                    <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                <?php endif ?>
            </address>
        </div><!-- .address-book__address-block -->
    </div><!-- .address-book__section -->
    <div class="address-book__section">
        <h2 class="address-book__section-title"><?php echo $this->__('Additional Address Entries') ?></h2>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <div class="address-book__address-block">
                <address class="address-book__address">
                    <p>
                        <?php echo $this->getAddressHtml($_address) ?>
                    </p>
                </address>
                <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> | <a class="js-delete-address" href="<?php echo $this->getDeleteUrl() . 'id/' . $_address->getId() ?>" data-question="<?php echo $this->__('Are you sure you want to delete this address?') ?>"><?php echo $this->__('Delete Address') ?></a></p>
            </div><!-- .address-book__address-block -->
            <?php endforeach; ?>
        <?php else: ?>
            <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
        <?php endif ?>
    </div><!-- .address-book__section -->
    <p class="address-book__add-new">
        <a href="<?php echo $this->getAddAddressUrl() ?>" class="address-book__add-new-address button"><?php echo $this->__('Add New Address') ?></a>
    </p>
    <p class="address-book__back-button">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="button button--invert"><?php echo $this->__('Back') ?></a>
    </p>
</div>
