<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="panel__header">
    <h2 class="panel__title"><span class="panel__title-text"><?php echo $this->__('My Account')?></span></h2>
    <button class="panel__close panel__action"><svg class="panel__action-icon panel__action-icon--close svg-icon"><use xlink:href="#icon-close" /></svg><span class="hide"><?php echo $this->__("Close") ?></span></button>
</div><!-- .panel__header -->

<div class="my-account panel__content">
    <div class="my-account__container panel__container">

        <ul class="list-group">

            <?php foreach ($this->getLinks() as $_link): ?>
                <li class="list-group__item">
                    <?php if ($this->isActive($_link)): ?>
                        <a class="list-group__item-title is-current" href="<?php echo $_link->getUrl() ?>">
                            <?php echo $_link->getLabel() ?>
                            <svg class="list-group__icon list-group__icon--current-nav svg-icon"><use xlink:href="#icon-checkmark" /></svg>
                        </a>
                    <?php else: ?>
                        <a class="list-group__item-title" href="<?php echo $_link->getUrl() ?>">
                            <?php echo $_link->getLabel() ?>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach;?>

            <li class="list-group__item"><a class="my-account__logout list-group__item-title" href="<?php echo $this->helper('customer')->getLogoutUrl() ?>"><?php echo $this->__("Logout") ?></a></li>
        </ul>

    </div><!-- .panel__container -->
</div><!-- .panel__content -->
