<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_option = $this->getOption() ?>
<?php $_optionId = $_option->getId() ?>

<div class="form__field<?php if ($_option->getIsRequire()): ?> form__field--required<?php endif; ?>">
    <label class="form__label<?php if ($_option->getIsRequire()): ?> form__label--required<?php endif; ?>"><?php echo $this->htmlEscape($_option->getTitle()) ?></label>
    <?php echo $this->getFormatedPrice() ?>

    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>

        <div class="product-options__date">
            <?php if ($this->useCalendar()): ?>
                <input class="form__textfield textfield" name="options[<?php echo $this->getOption()->getId() ?>][date]" onchange="opConfig.reloadPrice()" type="date" <?php if ($_option->getIsRequire()): ?>required<?php endif; ?>>
            <?php else: ?>
                <?php echo $this->getDateHtml() ?>

                <script>
                    Event.observe('options_<?php echo $_optionId ?>_month', 'change', dateOption.reloadMonth.bind(dateOption));
                    Event.observe('options_<?php echo $_optionId ?>_year', 'change', dateOption.reloadMonth.bind(dateOption));
                </script>
            <?php endif; ?>
        </div>

    <?php endif; ?>

    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
        || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_TIME): ?>
        <span class="product-options__time"><?php echo $this->getTimeHtml() ?></span>
    <?php endif; ?>

    <input type="hidden" name="validate_datetime_<?php echo $_optionId ?>" class="validate-datetime-<?php echo $_optionId ?>" value="">
    <script>
        <?php if ($_option->getIsRequire()): ?>
            Validation.addAllThese(
            [
                   ['validate-datetime-<?php echo $_optionId ?>', '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('This is a required option') )?>', function(v) {
                       var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                       for (var i=0; i < dateTimeParts.length; i++) {
                           if (dateTimeParts[i].value == "") return false;
                       }
                       return true;
                    }]
            ]
            );
        <?php else: ?>
            Validation.add(
                'validate-datetime-<?php echo $_optionId ?>',
                '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('Field is not complete') )?>',
                function(v) {
                    var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                    var hasWithValue = false, hasWithNoValue = false;
                    var pattern = /day_part$/i;
                    for (var i=0; i < dateTimeParts.length; i++) {
                       if (! pattern.test(dateTimeParts[i].id)) {
                           if (dateTimeParts[i].value === "") {
                               hasWithValue = true;
                           } else {
                               hasWithNoValue = true;
                           }
                       }
                    }
                    return hasWithValue ^ hasWithNoValue;
                }
            );
        <?php endif; ?>
    </script>

</div>
