<p>&nbsp;</p>
<div class="a-right"><a href="javascript:toggleDiv('comments_fullstock');"><?php echo Mage::helper('Orderpreparation')->__('Display / Hide Comments'); ?></a></div>
<div class="order_preparation_comments" id="comments_fullstock" name="comments_fullstock" <?php if (mage::getStoreConfig('orderpreparation/misc/show_order_comments') == 0) { echo 'style="display: none;"'; } ?>><?php echo $this->getAllComments(); ?></div>
<p>&nbsp;</p>
<?php echo $this->getGridParentHtml() ?>
