<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_product = $this->getProduct() ?>
<p class="nowrap">
	<!--Turning this input from hidden to textbox-->
	<input type="text" value="<?php echo max($this->getMinimalQty($_product), 1) ?>" class="add-to-cart__quantity" name="qty">
    <button type="button" class="button add-to-cart__submit js-add-to-cart orange-button" onclick="window.productAddToCartForm.submit()">
        <!--We want 'Add to cart' regardless of product type. Mohin - Aug 21, 2015-->
		<?php echo $this->__('Add to cart');?>
		<?php //if($_product->getHasOptions()): ?>
            <?php //echo $this->__('Configure and Buy');?>
        <?php //else: ?>
            <?php //echo $this->__('Add to cart');?>
        <?php //endif;?>
    </button>
</p>