<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    /* @var Mage_Wishlist_Model_Item $item */
    $item = $this->getItem();
    $product = $item->getProduct();
?>
<div class="wishlist-item__product product-card product-card--horizontal">
    <p class="product-card__image-wrapper">
        <a class="product-card__image-link" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
            <img class="product-card__image" src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(90) ?>" srcset="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(180) ?> 2x" width="90" height="90" alt="<?php echo $this->escapeHtml($product->getName()) ?>">
        </a>
    </p>
