<?php
//SCP: This is part of the Custom Option AJAX response - it shows custom options for 'associated' products.

//opConfig is forced into global scope even if pulled in via ajax (by using window.)
//and also ensure correct form encoding
?>
<script type="text/javascript">
	//<![CDATA[
	try{window.opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);}catch(e){}
	$('product_addtocart_form').encoding = 'multipart/form-data';
	//]]>
</script>
<?php if (count($this->getOptions())): ?>
<dl>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php foreach($_options as $_option): ?>
	<?php echo $this->getOptionHtml($_option) ?>
<?php endforeach; ?>
</dl>

<script type="text/javascript">
	$$('#product-options-wrapper dl').each(function(label) {
		label.removeClassName('last');
	});
	$$('#SCPcustomOptionsDiv dl').each(function(label) {
		label.addClassName('last');
	});
</script>
<?php endif; ?>

<?php /* Matthew: toggle for add to box and availability text */ ?>
<?php $_product = $this->getProduct(); ?>

<?php 
	$p_name = str_replace(' ', '', strtolower($_product->getName()));
	$salable = 0;
	$cart_loop=0;
	if(strstr($p_name,"-5kg")) {
		
		$productId = $_product->getId();
		$parentId  = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($productId);
		$childProductsId = Mage::getModel('catalog/product_type_configurable')->getChildrenIds($parentId[0]);
		$configurableProduct = Mage::getModel('catalog/product')->load($parentId[0]); 
		$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null,$configurableProduct);  
		foreach($childProducts as $child) {
			$childname = str_replace(' ', '', strtolower($child->getName()));
			if(strstr($childname,"-1kg")) {
				$load_product = Mage::getModel('catalog/product')->load($child->getId());
				$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($load_product);
				$p_qty = $stock->getQty();
				$stock_ordered_qty = $stock->getStockOrderedQty();
				$diffrence_qty = $p_qty - $stock_ordered_qty;
				if($p_qty<=$stock_ordered_qty || $diffrence_qty<5){
					$salable =1;
					break;	
				}
				
			}
		}
	}
 ?>

<script type="text/javascript">
<?php if ($_product->isSaleable() && $salable == 0): ?>
	jQuery('#product_addtocart_form .add-to-cart').show();
	jQuery('#product_addtocart_form .in-stock').show();
	jQuery('#product_addtocart_form .out-of-stock').hide();
<?php else: ?>
	jQuery('#product_addtocart_form .add-to-cart').hide();
	jQuery('#product_addtocart_form .in-stock').hide();
	jQuery('#product_addtocart_form .out-of-stock').show();
<?php endif; ?>
</script>
