
<table border="0" width="100%">
<tr>
	<th>Scan 1 :</th>
	<td class="a-center"><span id="scan_1"></span></td>
</tr>
<tr>
	<th>Scan 2 : </th>
	<td class="a-center"><span id="scan_2"></span></td>
</tr>
<tr>
	<th class="a-center" colspan="2">
		<p>&nbsp;</p>
		<span id="result" style="font-size: 24px; text-align: center;"></span>
	</th>
</tr>
</table>

<script>
	enableCatchKeys('compareScan();');
</script>