<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->canShow() && $this->getEvents() && count($this->getEvents())): ?>
    <div class="dashboard-section">
        <h2 class="dashboard-section__title"><?php echo Mage::helper('enterprise_customerbalance')->__('Balance History'); ?></h2>

        <div class="dashboard-section__content">
            <table class="storecredit-history">
                <thead>
                    <tr>
                        <th><?php echo Mage::helper('enterprise_customerbalance')->__('Action'); ?></th>
                        <th><?php echo Mage::helper('enterprise_customerbalance')->__('Balance Change'); ?></th>
                        <th><?php echo Mage::helper('enterprise_customerbalance')->__('Balance'); ?></th>
                        <th><?php echo Mage::helper('enterprise_customerbalance')->__('Date'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getEvents() as $event): ?>
                        <tr>
                            <td><?php echo $this->getActionLabel($event->getAction()); ?></td>
                            <td><?php echo Mage::helper('core')->currency($event->getBalanceDelta()); ?></td>
                            <td><?php echo Mage::helper('core')->currency($event->getBalanceAmount()); ?></td>
                            <td><?php echo Mage::helper('core')->formatDate($event->getUpdatedAt(), 'short', true); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>
