<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward_Info
 */
?>
<?php
$helper = Mage::helper('enterprise_reward');
$maxBalance = $this->getMaxBalance();
$minBalance = $this->getMinBalance();
$expireIn = $this->getExpireIn();
?>
<div class="dashboard-section reward-points-info">
    <h2 class="dashboard-section__title"><?php echo $this->__('Reward points balance Information'); ?> <span class="separator">|</span> <a href="<?php echo $helper->getLandingPageUrl() ?>"><?php echo $this->__('Learn more') ?></a></h2>

    <div class="dashboard-section__content">
        <p class="reward-points-info__item"><?php echo $this->__('Your current balance is %s.', '<strong>' . $helper->formatReward($this->getPointsBalance(), $this->getCurrencyBalance()) . '</strong>') ?></p>

        <div class="reward-points-info__item">
            <p class="reward-points-info__title"><?php echo $this->__('Current exchange rates:') ?></p>

            <?php if ($this->getPtsToAmountRateAmount() || $this->getAmountToPtsRatePts()): ?>
                <?php if ($this->getPtsToAmountRateAmount()): ?>
                    <p><?php echo $this->__('Each %s can be redeemed for %s.', $helper->formatReward($this-> getPtsToAmountRatePts(), null, null, '<strong>%s</strong>'), '<strong>' . $helper-> formatAmount($this->getPtsToAmountRateAmount()) . '</strong>') ?></p>
                <?php endif; ?>

                <?php if ($this->getAmountToPtsRatePts()): ?>
                    <p><?php echo $this->__('Each %s spent will earn %s.', '<strong>' . $helper->formatAmount( $this->getAmountToPtsRateAmount()) . '</strong>', $helper->formatReward($this-> getAmountToPtsRatePts(), null, null, '<strong>%s</strong>')) ?></p>
                <?php endif; ?>
            <?php else: ?>
                <p><?php echo $this->__('None.') ?></p>
            <?php endif; ?>
        </div>

        <?php if ($maxBalance || $minBalance): ?>
            <div class="reward-points-info__item">
                <p class="reward-points-info__title"><?php echo $this->__('Balance limitations:') ?></p>

                <?php if ($maxBalance): ?>
                    <p><?php echo $this->__('Balance is capped at %s.', $helper->formatReward($maxBalance)) ?></p>

                    <?php if ($this->getIsMaxBalanceReached()): ?>
                        <p class="warning"><?php echo $this->__('Maximum balance is reached.') ?></p>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($minBalance): ?>
                    <p><?php echo $this->__('Minimum Balance in order to redeem: %s.', $helper->formatReward($minBalance)) ?></p>

                    <?php if (!$this->getIsMinBalanceReached()): ?>
                        <p class="warning"><?php echo $this->__('Minimum balance for redeeming points is not reached.') ?></p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if ($expireIn): ?>
            <div class="reward-points-info__item">
                <p><?php echo $this->__('Each earned reward points record expires in %s days.', '<span>' . $expireIn . '</span>') ?></p>

                <?php if ($this->getIsHistoryPublished()): ?>
                    <p><?php echo $this->__('Refer to reward points history to see if a specific record expires and when.') ?></p>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
