<script>
    competitorPriceObj = new CompetitorPrice('<?php echo $this->getHostUrl(); ?>', <?php echo Mage::getStoreConfig('competitorprice/display/number_of_seller'); ?>, '<?php echo Mage::getStoreConfig('competitorprice/display/sort_mode'); ?>', '<?php echo $this->getConfigurationUrl(); ?>');

    Translator.add({"No barcode available":"<?php echo $this->__('No barcode available'); ?>"});
    Translator.add({"Matching in progress, please wait":"<?php echo $this->__('Matching in progress, please wait'); ?>"});
    Translator.add({"No result":"<?php echo $this->__('No result'); ?>"});

    Translator.add({"Competitor":"<?php echo $this->__('Competitor'); ?>"});
    Translator.add({"Price":"<?php echo $this->__('Price'); ?>"});
    Translator.add({"Shipping":"<?php echo $this->__('Shipping'); ?>"});
    Translator.add({"Total":"<?php echo $this->__('Total'); ?>"});

    Translator.add({"See on":"<?php echo $this->__('See on'); ?>"});
    Translator.add({"offers for this product":"<?php echo $this->__('offers for this product'); ?>"});

    Translator.add({"Watch this product":"<?php echo $this->__('Watch this product'); ?>"});

    Translator.add({"No offer for this product":"<?php echo $this->__('No offer for this product'); ?>"});
    Translator.add({"This product is excluded":"<?php echo $this->__('This product is excluded'); ?>"});

    Translator.add({"please check your configuration":"<?php echo $this->__('please check your configuration'); ?>"});

    Translator.add({"Your credits are over":"<?php echo $this->__('Your credits are over'); ?>"});
    Translator.add({"buy credits":"<?php echo $this->__('buy credits'); ?>"});

</script>
