<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="related-products">
        <h3 class="related-products__title"><?php echo $this->__('New Products') ?></h3>
        <div class="related-products__list">
            <?php foreach($_products as $_item): ?>
                <a class="related-products__product product-card product-card--related" href="<?php echo $_item->getProductUrl() ?>">
                    <p class="product-card__image-wrapper">
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(118); ?>" srcset="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(236); ?> 2x" width="118" height="118" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-card__image">
                    </p>
                    <div class="product-card__info">
                        <h3 class="product-card__title product-card__title--trimmed">
                            <?php echo $this->htmlEscape($_item->getName()) ?>
                        </h3>
                        <?php echo $this->getReviewsSummaryHtml($_item, 'short', false)?>
                        <?php echo $this->getPriceHtml($_item, true, '-related');?>
                    </div><!-- .product-card__info -->
                </a>
            <?php endforeach ?>
        </div>
    </div>
<?php endif; ?>
