<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $_item = $this->getItem();
    $canApplyMsrp = false;
    if(method_exists(Mage::helper('catalog'), 'canApplyMsrp')) {
        $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp(
            $_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM
        );
    }
?>

<div class="cart__item cart-item" data-item-id="<?php echo $this->getItem()->getId() ?>">
    <div class="cart-item__product product-card product-card--horizontal">
        <p class="product-card__image-wrapper">
            <?php if ($this->hasProductUrl()): ?>
                <a class="product-card__image-link" href="<?php echo $this->getProductUrl() ?>">
                    <img class="product-card__image" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" src="<?php echo $this->getProductThumbnail()->resize(90); ?>" srcset="<?php echo $this->getProductThumbnail()->resize(180); ?> 2x" width="90" height="90">
                </a>
            <?php else: ?>
                <img class="product-card__image" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" src="<?php echo $this->getProductThumbnail()->resize(90); ?>" srcset="<?php echo $this->getProductThumbnail()->resize(180); ?> 2x" width="90" height="90">
            <?php endif; ?>
        </p>

        <div class="product-card__info">
            <h3 class="product-card__title">
                <?php if ($this->hasProductUrl()): ?>
                    <a class="product-card__title-link" href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $this->htmlEscape($this->getProductName()) ?>
                <?php endif; ?>
            </h3>

            <p class="product-card__price">
                <?php
                    $cartBothPrices = false;
                ?>
                <?php if (($this->helper('tax')->displayCartPriceExclTax() || $cartBothPrices = $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>
                            <?php if($cartBothPrices): ?>
                                <span class="price-excluding-tax">
                                    <span class="label"><?php echo $this->__('Excl. Tax'); ?></span>
                            <?php endif; ?>
                                    <?php if ($canApplyMsrp): ?>
                                        <span class="cart-msrp-subtotal">--</span>
                                    <?php else: ?>
                                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                                        <?php else: ?>
                                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                            <?php if($cartBothPrices): ?>
                                </span>
                            <?php endif; ?>
		            </span>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

			            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>

                <?php
                    $cartBothPrices = false;
                ?>
                <?php if (($this->helper('tax')->displayCartPriceInclTax() || $cartBothPrices = $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
                    <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
		            <?php else: ?>
                        <span class="cart-price">
		            <?php endif; ?>
                            <?php if($cartBothPrices): ?>
                                <span class="price-including-tax">
                                    <span class="label"><?php echo $this->__('Incl. Tax'); ?></span>
                            <?php endif; ?>
                                    <?php if ($canApplyMsrp): ?>
                                        <span class="cart-msrp-subtotal">--</span>
                                    <?php else: ?>
                                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                            <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                                        <?php else: ?>
                                            <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                            <?php if($cartBothPrices): ?>
                                </span>
                            <?php endif; ?>
    		        </span>

                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
		                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>

            <?php if ($_options = $this->getOptionList()): ?>
                <?php foreach ($_options as $_option): ?>
                    <p class="product-card__option">
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                        <strong><?php echo $this->htmlEscape($_option['label']) ?>:</strong> <?php echo $_formatedOptionValue['value'] ?>
                    </p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($_item->getProduct()->isSaleable()): ?>
                <p class="cart-item__availability product-card__availability"><?php echo $this->__('In stock') ?></p>
            <?php else: ?>
                <p class="cart-item__availability product-card__availability"><?php echo $this->__('Out of stock') ?></p>
            <?php endif; ?>

            <?php if ($messages = $this->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php /* downloadable */ ?>
            <?php if ($links = $this->getLinks()): ?>
                <div class="product-card__option">
                    <?php echo $this->getLinksTitle() ?>:

                    <?php foreach ($links as $link): ?>
                        <p class="product-option product-sub-option">
                            <?php echo $link->getTitle() ?>
                        </p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        </div>
    </div>

    <div class="cart-item__controls">
        <input class="cart-item__quantity" type="tel" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" class="input-text qty" maxlength="12">

        <button class="cart-item__update js-update-cart" type="submit"><?php echo $this->__('Update Cart') ?></button>

        <button class="cart-item__delete cart-item__button js-delete-product-from-cart" type="button" data-delete-url="<?php echo $this->helper('aw_mobile3/url')->getCartDeleteUrl($this->getItem()->getId()) ?>"><svg class="cart-item__delete-icon svg-icon"><use xlink:href="#icon-delete" /></svg><?php echo $this->__('Delete') ?></button>

        <?php if ($this->helper('aw_mobile3')->getIsCanShowUpdateButton()): ?>
            <a class="cart-item__edit cart-item__button" href="<?php echo $this->getConfigureUrl() ?>"><?php echo $this->__('Edit') ?></a>
        <?php endif; ?>
    </div>
</div>
