<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Helpdeskultimate
 * @version    2.10.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-head">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_orders->getSize()): ?>
<table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
    <tr>
        <th><?php echo $this->__('Order #') ?></th>
        <th><?php echo $this->__('Date') ?></th>
        <th><?php echo $this->__('Ship to') ?></th>
        <th><?php echo $this->__('Order Total') ?></th>
        <th><?php echo $this->__('Order Status') ?></th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
    <tr>
        <td><?php echo $_order->getRealOrderId() ?></td>
        <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
        <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName())
                : '&nbsp;' ?></td>
        <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
        <td><em><?php echo $_order->getStatusLabel() ?></em></td>
        <td class="a-center"><a
                href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
            <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>"
                                                    style="font-weight: bold; color: #FF6600;"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
            <?php if (Mage::getStoreConfig('helpdeskultimate/advanced/orders_enabled')): ?>
                <span class="separator">|</span> <a
                        href="<?php echo Mage::getUrl('helpdeskultimate/customer', array('order' => $_order->getId()))?>#ticket-create-form"><?php echo Mage::helper('helpdeskultimate')->__('Create ticket');?></a>
                <?php endif;?>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
<p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
