<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    if ($this->_getMinimumAmountNotice()) {
        Mage::getSingleton('checkout/session')->addNotice($this->_getMinimumAmountNotice());
    }
    $cartMessages = $this->getMessagesBlock()->addMessages(Mage::getSingleton('checkout/session')->getMessages(true))->getGroupedHtml();
?>

<?php if ($cartMessages): ?>
    <div class="cart__messages">
        <?php echo $cartMessages ?>
    </div>
<?php endif ?>

<?php echo $this->getChildHtml('form_before') ?>

<form class="cart__items" id="update_cart_form" action="<?php echo $this->helper('aw_mobile3/url')->getCartUpdateUrl() ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <?php foreach($this->getItems() as $_item): ?>
        <?php if($_item->getQty()): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endif ?>
    <?php endforeach ?>
</form>

<div class="cart__bottom">
    <p class="cart__discount">
        <button class="cart__apply-discount button button--alternative-invert js-open-panel" data-open-panel="discount" id="discount_container_link" type="button">
            <?php echo $this->__("Apply Discount")?>
            <svg class="cart__apply-discount-icon svg-icon"><use xlink:href="#icon-list-arrow" /></svg>
        </button>
    </p><!-- .cart__discount -->

    <h3 class="cart__summary-title"><?php echo $this->__('Summary')?></h3>

    <?php echo $this->getChildHtml('totals'); ?>

    <?php if (!$this->hasError()): ?>
        <?php echo $this->getChildHtml('checkout.cart.methods.onepage'); ?>
    <?php endif; ?>

</div>