<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="forgot-password panel__container" data-container="forgot-password" data-title="<?php echo $this->__('Forgot Your Password?') ?>">
    <form class="form" action="<?php echo $this->helper('aw_mobile3/url')->getForgotPostUrl() ?>" method="post" id="user_forgotpassword_form">

        <p class="form__field"><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>

        <p class="form__field">
            <label class="form__label form__label--required" for="email_address_forgot"><?php echo $this->__('Email Address') ?></label>
            <input class="form__textfield textfield validate-email required-entry" type="email" name="email" id="email_address_forgot" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>">
        </p><!-- .form__field -->

        <?php echo $this->getChildHtml('form.additional.info'); ?>

        <p class="form__field">
            <button class="form__submit button" type="submit"><?php echo $this->__('Submit') ?></button>
        </p><!-- .form__field -->

    </form>

    <div class="panel__container-shadow"></div>
</div><!-- .panel__container -->
