<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile2
 * @version    2.0.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?php echo $this->getChildHtml('external.pagecache.cookie') ?>
<div class="product__product-card product-card">
    <div class="product-info">
        <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
        <div class="product-name">
            <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
        </div>
        <?php echo $this->getReviewsSummaryHtml($_product, false, false)?>
    </div>
    <?php echo $this->getChildHtml('product.info.gallery');?>
    <div class="product-info-form">
        <form class="product-card__add-to-cart add-to-cart" id="product_addtocart_form" action="<?php echo $this->helper('aw_mobile2/url')->getAddToCartUrl($_product, array(), $this->getData('submit_route_data')) ?>" method="post" id="product_addtocart_form" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-type-data-container">
                <?php if (!$_product->getTypeInstance() instanceof Mage_Catalog_Model_Product_Type_Grouped):?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                <?php endif;?>
                <?php echo $this->getChildHtml('product_options_wrapper');?>
                <?php echo $this->getTierPriceHtml() ?>
                <?php if($_product->isSaleable()): ?>
                    <?php echo $this->getChildHtml('addtocart') ?>
                <?php endif; ?>
                <?php if ($_product->getTypeInstance() instanceof Mage_Catalog_Model_Product_Type_Grouped):?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                <?php endif;?>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    window.productAddToCartForm = new awMobile2.app.ajaxAddProductToCart('product_addtocart_form');
    window.productAddToCartForm.submit = function(){
        //The bellow vode does not work after installation. Not investing time to fix it since we do not need this feature. Work on it in future if needed. Mohin-Aug 09, 2015
		<?php //if ($this->hasOptions()): ?>
        <?php //if ($this->hasOptions()): ?>
        //window.optionPopup = new awMobile2.app.popup();
        //window.optionPopup.open($('product-options-wrapper'), <?php echo Zend_Json::encode($_product->getName());?>, '', function() {}, false);
        <?php //else :?>
        //this.sendRequest();
        <?php //endif; ?>		
		this.sendRequest();
    }.bind(window.productAddToCartForm);
    //]]>
</script>
<?php echo $this->getChildHtml('info_tabs') ?>
<!--According to google adwords, we need to add these disclaimers at the end. Mohin, 25 Nov 2015 -->
<?php if($_product->getAddLegalDisclaimer()): ?>
	<p class="add-legal-disclaimer">*NOTE: These statements have not been evaluated by the Food and Drug Administration.  This product is not intended to diagnose, treat, cure or prevent any disease.</p>
	<p class="add-legal-disclaimer">**DISCLAIMER: There is no guarantee of specific results and results can vary.</p>
<?php endif; ?>