<script>
	var postamble = '<?php echo mage::getStoreConfig('scanner/misc/postamble'); ?>';
</script>

<style>
    .div_toolbar
    {
            background-color: #ffffff;
            border-style: solid;
            border-width: 1px;
            text-align: center;
            position: absolute;
            top: <?php echo (mage::getStoreConfig('scanner/display/screen_height') - 30); ?>px;
            left: 0px;
            width: <?php echo mage::getStoreConfig('scanner/display/screen_width'); ?>px;
            height: 30px;
    }

    .div_barcode
    {
            border-style: solid;
            border-width: 1px;
            text-align: center;
            background-color: #ffffff;
            height: 20px;
            width: 150px;
    }

    th
    {
        padding: 0px;
        spacing: 0px;
    }

    td
    {
        padding: 0px;
        spacing: 0px;
    }

    .touch_button
    {

    }

    .touch_button_menu
    {
        width: 170px;
    }
}
}

</style>

<div id="div_toolbar" name="div_toolbar" class="div_toolbar">

<table width="100%" border="0">
<tr>
	<td><div id="barcode" name="barcode" class="div_barcode"></div></td>
	<td><input type="button" value=" Menu " onclick="document.location.href='<?php echo $this->getMenuUrl(); ?>'"></td>
</tr>
</table>

	<!-- hidden form -->
	<form method="POST" action="<?php echo $this->getSubmitUrl(); ?>" name="form1" id="form1">
		<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" id="query" name="query">
	</form>

</div>
