<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
// Added for restrict country feature - Mohin, 25 Oct 2015
// We have added this code again for updating mobile theme 2.0.6 to 3.0.3. Erik, 11 Nov 2016, mantis-400
$nonShippableProducts = Mage::helper('restrictcountry')->getNonShippableProducts();
?>
<?php
// Check if there is non shippable products  - Mohin, 25 Oct 2015
if(count($nonShippableProducts)>0) {
?>
<div class="restricted-products">
    <div class="error-msg items-remove">
        <p><strong><?php echo $this->__('Warning!') ?></strong></p>
        <p><?php echo $this->__('The following items are not available for shipment to your country and will be remove from your cart!') ?></p>
    </div>
    <table class="data-table" style="overflow-x:auto;">
        <thead>
            <tr>
                <th><?php echo $this->__('Name') ?></th>
                <th><?php echo $this->__('Sku') ?></th>
                <th><?php echo $this->__('Price') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($nonShippableProducts as $product){ ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($product->getName()) ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($product->getSku()) ?>
                </td>
                <td>
                    <?php echo $this->helper('core')->formatPrice($product->getFinalPrice()) ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>
<!--Original Code-->
<?php if (!$this->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
