<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Stock Errors')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getUrl('AdvancedStock/Misc/MassFixErrors'); ?>'" class="scalable" type="button"><span><?php echo $this->__('Mass fix errors')?></span></button>
                <button onclick="document.location.href='<?php echo $this->getUrl('AdvancedStock/Misc/RefreshErrorList'); ?>'" class="scalable" type="button"><span><?php echo $this->__('Refresh cache')?></span></button>
            </td>        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>

</div>