<div class="supp-facts">
    <h2>Supplement Facts</h2>
    <span>Serving size: 1/16 teaspoon (200mg)</span><br />
    <span>Serving per container: *</span>
    <table>
      <colgroup>
        <col width="70%" />
        <col width="30%" />
      </colgroup>
      <thead>
        <tr>
            <th>
                <strong>Amount Per Serving<br />Calories: 35<br />Calories from Fat: 5</strong>
            </th>
            <th><strong>% Daily Value**</strong></th>
        </tr>        
      </thead>
      <tbody>
        <tr>
            <td>Total Fat &lt; 1 g</td>
            <td class="a-right">&lt;1%</td>
        </tr>
        <tr>
            <td>Carbohydrate 1.98g</td>
            <td class="a-right">&lt;1%</td>
        </tr>
        <tr>
            <td>Protein 5.7g</td>
            <td class="a-right">11%</td>
        </tr>
      </tbody>
    </table>
    <div>
        * Daily Value not established.<br />
        ** Based on 2,000 calorie diet
    </div>
</div>

<p><label>Other Ingredients:</label> None</p>
<p><label>Free of:</label> Sugar, Soy, dairy, yeast, gluten or additives</p>
<p><label>Directions:</label> As a dietary supplement, take 50 to 200 mg (1/6 tsp) up to three times daily. DO NOT use more than 200mg in a single serving, or more than 600 mg in a day...</p>

<table class="us-spoons">
    <thead>
        <tr>
            <th colspan="2" class="a-center">US Standard Measuring Spoons</th>
        </tr>
        <tr>
            <th>Spoon Size(level)</th>
            <th class="a-right">milligrams</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1/16 teaspoon</td>
            <td class="a-right">189</td>
        </tr>
        <tr>
            <td>1/8 teaspoon</td>
            <td class="a-right">378</td>
        </tr>
        <tr>
            <td>1/4 teaspoon</td>
            <td class="a-right">756</td>
        </tr>
    </tbody>    
</table>
