<div class="entry-edit">
    
	    <div class="entry-edit-head"> 
		    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Accounting'); ?></h4> 
	    </div>
	    
		<fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Invoice Date'); ?></td>
                    <td class="input-ele">
                    	<input size="8" type="text" id="po_invoice_date" name="po_invoice_date" value="<?php echo $this->getOrder()->getpo_invoice_date(); ?>">
                    	<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" id="img_calendar_invoice_date" />
				        <script type="text/javascript">
			                Calendar.setup({
			                    inputField : 'po_invoice_date',
			                    ifFormat : '%Y-%m-%e',
			                    button : 'img_calendar_invoice_date',
			                    align : 'Bl',
			                    singleClick : true
			                });
		                </script>

                        <?php if ($dueDate = $this->getOrder()->getInvoiceDueDate()): ?>
                            <i>(<?php echo $this->__('Due date is %s', $this->formatDate($dueDate, 'medium')); ?>)</i>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Invoice Ref'); ?></td>
                    <td class="input-ele"><input type="text" name="po_invoice_ref" id="po_invoice_ref" value="<?php echo $this->getOrder()->getpo_invoice_ref(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Payment Date'); ?></td>
                    <td class="input-ele">
                    	<input size="8" type="text" id="po_payment_date" name="po_payment_date" value="<?php echo $this->getOrder()->getpo_payment_date(); ?>">
                    	<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" id="img_calendar_payment_date" />
				        <script type="text/javascript">
			                Calendar.setup({
			                    inputField : 'po_payment_date',
			                    ifFormat : '%Y-%m-%e',
			                    button : 'img_calendar_payment_date',
			                    align : 'Bl',
			                    singleClick : true
			                });
		                </script>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Supplier Order Ref'); ?></td>
                    <td class="input-ele">
					<input type="text" name="po_supplier_order_ref" id="po_supplier_order_ref" value="<?php echo $this->getOrder()->getpo_supplier_order_ref(); ?>">
                    </td>
                </tr>
                <tr>
                	<td class="label"><?php echo $this->__('Extended costs are external'); ?></td>
                	<td class="input-ele"><?php echo $this->getBooleanCombo('po_external_extended_cost', $this->getOrder()->getpo_external_extended_cost()); ?></td>
                </tr>
                <tr>
                	<td class="label"><?php echo $this->__('Datas verified'); ?></td>
                	<td class="input-ele"><?php echo $this->getBooleanCombo('po_data_verified', $this->getOrder()->getpo_data_verified()); ?></td>
                </tr>
                <tr>
                	<td class="label"><?php echo $this->__('Paid'); ?></td>
                	<td class="input-ele"><?php echo $this->getBooleanCombo('po_paid', $this->getOrder()->getpo_paid()); ?></td>
                </tr>                
            </table>
        </fieldset>
	    
</div>