<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Supplier List')?></h3></td>
            <td align="right">
                <?php if (Mage::getSingleton('admin/session')->isAllowed('admin/erp/purchasing/purchase_supplier/create')): ?>
                    <button onclick="document.location.href='<?php echo $this->getNewUrl()?>'" class="scalable save" type="button"><span><?php echo $this->__('New')?></span></button>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>

</div>