<?php $_data = $this->getFormData(); ?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Create your account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <p><?php echo $this->__('Use this form if you want to create an account for an order that you previously placed as a guest.'); ?></p>

    <p><?php echo $this->__('To attach an existing order to this new account, please enter the order number in the appropriate field.'); ?></p>

    <div class="col2-set">

        <div class="col-1 new-users">
            <form action="<?php echo $this->getUrl('*/*/Submit') ?>" method="post" id="form-validate">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                        </li>
                        <li>
                            <label for="email_address"
                                   class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                            </label>

                            <div class="input-box">
                                <input type="text" name="email" id="email_address"
                                       value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>"
                                       title="<?php echo $this->__('Email Address') ?>"
                                       class="input-text validate-email required-entry"/>
                            </div>
                        </li>
                        <?php if ($this->isNewsletterEnabled()): ?>
                            <li class="control">
                                <div class="input-box">
                                    <input type="checkbox" name="is_subscribed"
                                           title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1"
                                           id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                           class="checkbox"/>
                                </div>
                                <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                            </li>
                        <?php endif ?>
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                        <?php endif ?>
                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                        <?php endif ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                        <?php endif ?>
                        <li class="fields">
                            <div class="field">
                                <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?>
                                </label>

                                <div class="input-box">
                                    <input type="password" name="password" id="password"
                                           title="<?php echo $this->__('Password') ?>"
                                           class="input-text required-entry validate-password"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="confirmation"
                                       class="required"><em>*</em><?php echo $this->__('Confirm Password') ?>
                                </label>

                                <div class="input-box">
                                    <input type="password" name="confirmation"
                                           title="<?php echo $this->__('Confirm Password') ?>"
                                           id="confirmation" class="input-text required-entry validate-cpassword"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="order_id" class="required"><em>*</em><?php echo $this->__('Order number') ?>
                                </label>

                                <div class="input-box">
                                    <input type="text" name="order_id" id="order_id"
                                           title="<?php echo $this->__('Order number') ?>"
                                           class="input-text required-entry" value="<?php echo $_data['order_id']; ?>"/>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <p class="required" style="margin:0;"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="buttons-set">
                    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"
                                            class="back-link">
                            <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                    <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button">
                        <span><span><?php echo $this->__('Submit') ?></span></span></button>
                </div>
            </form>
        </div>
        <div class="col-2 registered-users">
            <form action="<?php echo $this->helper('customer')->getLoginPostUrl(); ?>" method="post" id="login-form">
                <div class="content">
                    <h2><?php echo $this->__('Registered Customers') ?></h2>

                    <p><?php echo $this->__('If you have an existing account, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                            </label>

                            <div class="input-box">
                                <input type="text" name="login[username]"
                                       value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email"
                                       class="input-text required-entry validate-email"
                                       title="<?php echo $this->__('Email Address') ?>"/>
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                            <div class="input-box">
                                <input type="password" name="login[password]"
                                       class="input-text required-entry validate-password" id="pass"
                                       title="<?php echo $this->__('Password') ?>"/>
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>"
                       class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send"
                            id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        var dataLoginForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>