<script>

    //******************************************************************************************
    //Save changes
    function saveData()
    {
        //store changes in input
        persistantGrid.storeLogInTargetInput();
    
        //submit form
        document.getElementById('frm').submit();
    }

    //******************************************************************************************
    //toggle texbox disable depending of the checkbox
    function toggleTextboxDisable(checkBox, textId)
    {
        elt = document.getElementById(textId);
        if (elt)
            elt.disabled  = checkBox.checked;
    }
    
    //******************************************************************************************
    //
    function synchronizeCheckboxes(id)
    {
        if (parseInt(id))
        {
            toggleTextboxDisable(document.getElementById('use_config_ideal_stock_level_' + id), 'ideal_stock_level_' + id);
            toggleTextboxDisable(document.getElementById('use_config_notify_stock_qty_' + id), 'notify_stock_qty_' + id);
        }
    }

</script>

<form id="frm" name="frm" method="POST" action="<?php echo $this->getUrl('*/*/MassStockSave'); ?>">
    <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <input type="hidden" size="100" name="mass_stock_editor_logs" id="mass_stock_editor_logs" value="">
</form>

<div class="entry-edit">

    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo$this->__('Mass Stock Editor') ?></h3></td>
                <td align="right">
                    <button onclick="saveData();" class="scalable save" type="button"><span><?php echo $this->__('Save') ?></span></button>
                </td>
            </tr>
        </table>
    </div>

    <?php echo $this->getGridParentHtml() ?>
    <script>persistantGrid = new persistantGridControl(MassStockEditorGridJsObject, 'mass_stock_editor_logs', 'qty_', synchronizeCheckboxes);</script>

</div>