-- IMPORT PROFILE FOR ERP

INSERT INTO `dataflow_profile` (`name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES
('Import product / warehouse stock levels', '2011-01-17 13:09:32', '2011-01-17 13:09:32', '<!-- file import -->\r\n<action type=\"dataflow/convert_adapter_io\" method=\"load\">\r\n    <var name=\"type\">file</var>\r\n    <var name=\"path\">var/import</var>\r\n    <var name=\"filename\"><![CDATA[product_warehouse_stock_level.csv]]></var>\r\n    <var name=\"format\"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<!-- file parser -->\r\n<action type=\"dataflow/convert_parser_csv\" method=\"parse\">\r\n    <var name=\"delimiter\"><![CDATA[;]]></var>\r\n    <var name=\"fieldnames\">true</var>\r\n    <var name=\"decimal_separator\"><![CDATA[.]]></var>\r\n    <var name=\"method\">parse</var>\r\n    <var name=\"adapter\">AdvancedStock/Convert_Adapter_ProductWarehouseStock</var>\r\n    <var name=\"method\">saveRow</var>\r\n</action>\r\n', NULL, NULL, '', 0, NULL),
('Import product barcodes', '2011-01-18 10:27:41', '2011-01-18 10:27:41', '<!-- file import -->\r\n<action type=\"dataflow/convert_adapter_io\" method=\"load\">\r\n    <var name=\"type\">file</var>\r\n    <var name=\"path\">var/import</var>\r\n    <var name=\"filename\"><![CDATA[product_barcodes.csv]]></var>\r\n    <var name=\"format\"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<!-- file parser -->\r\n<action type=\"dataflow/convert_parser_csv\" method=\"parse\">\r\n    <var name=\"delimiter\"><![CDATA[;]]></var>\r\n    <var name=\"fieldnames\">true</var>\r\n    <var name=\"decimal_separator\"><![CDATA[.]]></var>\r\n    <var name=\"method\">parse</var>\r\n    <var name=\"adapter\">AdvancedStock/Convert_Adapter_ImportBarcode</var>\r\n    <var name=\"method\">saveRow</var>\r\n</action>\r\n', NULL, NULL, '', 0, NULL),
('Export sales history', '2011-08-29 15:09:44', '2011-08-29 15:09:44', '<action type=\"AdvancedStock/Convert_Adapter_SalesHistory\" method=\"save\">\r\n    <var name=\"type\">file</var>\r\n    <var name=\"path\">var/export</var>\r\n    <var name=\"filename\"><![CDATA[sales_history.csv]]></var>\r\n </action>', NULL, NULL, '', 0, NULL);

INSERT INTO `dataflow_profile` (`name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES
('Export Order To Prepare', '2009-11-12 07:53:42', '2009-11-12 07:54:12', '<action type=\"Orderpreparation/convert_adapter_OrderToPrepare\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_ordertoprepare.csv]]></var>    <var name=\"fields\"><![CDATA[order_id;id;shipment_id;invoice_id;real_weight;force_invoice_date;ship_mode;package_count;details;entity_id;entity_type_id;attribute_set_id;increment_id;parent_id;store_id;created_at;updated_at;is_active;customer_id;tax_amount;shipping_amount;discount_amount;subtotal;grand_total;total_paid;total_refunded;total_qty_ordered;total_canceled;total_invoiced;total_online_refunded;total_offline_refunded;base_tax_amount;base_shipping_amount;base_discount_amount;base_subtotal;base_grand_total;base_total_paid;base_total_refunded;base_total_qty_ordered;base_total_canceled;base_total_invoiced;base_total_online_refunded;base_total_offline_refunded;subtotal_refunded;subtotal_canceled;discount_refunded;discount_canceled;discount_invoiced;tax_refunded;tax_canceled;shipping_refunded;shipping_canceled;base_subtotal_refunded;base_subtotal_canceled;base_discount_refunded;base_discount_canceled;base_discount_invoiced;base_tax_refunded;base_tax_canceled;base_shipping_refunded;base_shipping_canceled;subtotal_invoiced;tax_invoiced;shipping_invoiced;base_subtotal_invoiced;base_tax_invoiced;base_shipping_invoiced;shipping_tax_amount;base_shipping_tax_amount;shipping_tax_refunded;base_shipping_tax_refunded;stocks_updated]]></var></action>', '', NULL, '', 0, NULL),
('Export Order To Prepare Pending', '2009-11-12 07:56:02', '2009-11-12 07:56:02', '<action type=\"Orderpreparation/convert_adapter_OrderToPreparePending\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_ordertopreparepending.csv]]></var>    <var name=\"fields\"><![CDATA[opp_num;opp_order_id;opp_type;opp_shipto_name;opp_remain_to_ship;opp_details;opp_order_increment_id;entity_id;entity_type_id;attribute_set_id;increment_id;parent_id;store_id;created_at;updated_at;is_active;customer_id;tax_amount;shipping_amount;discount_amount;subtotal;grand_total;total_paid;total_refunded;total_qty_ordered;total_canceled;total_invoiced;total_online_refunded;total_offline_refunded;base_tax_amount;base_shipping_amount;base_discount_amount;base_subtotal;base_grand_total;base_total_paid;base_total_refunded;base_total_qty_ordered;base_total_canceled;base_total_invoiced;base_total_online_refunded;base_total_offline_refunded;subtotal_refunded;subtotal_canceled;discount_refunded;discount_canceled;discount_invoiced;tax_refunded;tax_canceled;shipping_refunded;shipping_canceled;base_subtotal_refunded;base_subtotal_canceled;base_discount_refunded;base_discount_canceled;base_discount_invoiced;base_tax_refunded;base_tax_canceled;base_shipping_refunded;base_shipping_canceled;subtotal_invoiced;tax_invoiced;shipping_invoiced;base_subtotal_invoiced;base_tax_invoiced;base_shipping_invoiced;shipping_tax_amount;base_shipping_tax_amount;shipping_tax_refunded;base_shipping_tax_refunded;stocks_updated]]></var></action>', NULL, NULL, '', 0, NULL),
('Export Order To Prepare Items', '2009-11-12 07:57:32', '2009-11-12 07:59:32', '<action type=\"Orderpreparation/convert_adapter_OrderToPrepareItems\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_ordertoprepareitems.csv]]></var>    <var name=\"fields\"><![CDATA[order_id;product_id;qty;id;is_config;order_item_id;item_id;order_id;parent_item_id;quote_item_id;created_at;updated_at;product_id;product_type;product_options;weight;is_virtual;sku;name;description;applied_rule_ids;additional_data;free_shipping;is_qty_decimal;no_discount;qty_backordered;qty_canceled;qty_invoiced;qty_ordered;qty_refunded;qty_shipped;cost;price;base_price;original_price;base_original_price;tax_percent;tax_amount;base_tax_amount;tax_invoiced;base_tax_invoiced;discount_percent;discount_amount;base_discount_amount;discount_invoiced;base_discount_invoiced;amount_refunded;base_amount_refunded;row_total;base_row_total;row_invoiced;base_row_invoiced;row_weight;gift_message_id;gift_message_available;base_tax_before_discount;tax_before_discount;ext_order_item_id;locked_do_invoice;locked_do_ship;weee_tax_applied;weee_tax_applied_amount;weee_tax_applied_row_amount;base_weee_tax_applied_amount;base_weee_tax_applied_row_amount;weee_tax_disposition;weee_tax_row_disposition;base_weee_tax_disposition;base_weee_tax_row_disposition;comments;reserved_qty]]></var></action>', '', NULL, '', 0, NULL);

INSERT INTO `dataflow_profile` (`name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES
('Export Purchase Order', '2009-10-13 06:26:39', '2009-11-12 14:21:16', '<action type=\"Purchase/convert_adapter_orders\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_orders.csv]]></var>    <var name=\"fields\"><![CDATA[po_num;po_sup_num;sup_name;po_date;po_order_id;po_supply_date;po_carrier;po_payment_type;po_currency;po_invoice_date;po_invoice_ref;po_paid;po_sent;po_currency_change_rate;po_shipping_cost;po_shipping_cost_base;po_zoll_cost;po_zoll_cost_base;po_finished;po_tax_rate;po_mediabox_num;po_comments;po_payment_date;po_supplier_order_ref;po_status;po_delivery_percent;po_supplier_notification_date]]></var></action>', '', NULL, '', 0, NULL),
('Export Purchase Order Products', '2009-11-12 06:33:31', '2009-11-12 14:26:15', '<action type=\"Purchase/convert_adapter_orders_products\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_orders_products.csv]]></var>    <var name=\"fields\"><![CDATA[pop_num;pop_order_num;pop_product_id;sku;pop_product_name;pop_qty;pop_supplied_qty;pop_price_ht;pop_price_ht_base;pop_supplier_ref;pop_eco_tax;pop_eco_tax_base;pop_extended_costs;pop_extended_costs_base;pop_tax_rate]]></var></action>', '', NULL, '', 0, NULL),
('Export Suppliers', '2009-11-12 06:40:51', '2009-11-12 06:41:29', '<action type=\"Purchase/convert_adapter_suppliers\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_suppliers.csv]]></var>    <var name=\"fields\"><![CDATA[sup_id;sup_name;sup_address1;sup_address2;sup_zipcode;sup_country;sup_city;sup_tel;sup_fax;sup_contact;sup_mail;sup_website;sup_sale_online;sup_account_login;sup_account_password;sup_order_mini;sup_supply_delay;sup_supply_delay_max;sup_carrier;sup_comments;sup_rma_tel;sup_rma_mail;sup_rma_comments;sup_mediabox_id]]></var></action>', '', NULL, '', 0, NULL),
('Export Contact', '2009-11-12 06:43:30', '2009-11-12 06:45:02', '<action type=\"Purchase/convert_adapter_contacts\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_contacts.csv]]></var>    <var name=\"fields\"><![CDATA[pc_num;pc_lastname;pc_firstname;pc_function;pc_phone;pc_fax;pc_mobile;pc_email;pc_comments;pc_type;pc_entity_id;pc_country]]></var></action>', '', NULL, '', 0, NULL),
('Export Products (purchase view)', '2009-11-12 06:54:04', '2009-11-12 06:54:04', '<action type=\"Purchase/convert_adapter_products\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_products.csv]]></var>    <var name=\"fields\"><![CDATA[sku;name;cost;price;margin;stock_qty;real_notify_stock_qty;ordered_qty;qty_needed]]></var></action>', NULL, NULL, '', 0, NULL),
('Export Products Stock Movements', '2009-11-12 06:56:59', '2009-11-12 07:11:19', '<action type=\"AdvancedStock/convert_adapter_stockmovements\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_stockmovements.csv]]></var>    <var name=\"fields\"><![CDATA[sku;sm_id;sm_product_id;sm_qty;sm_coef;sm_description;sm_type;sm_date;sm_estimated_date;sm_ui;sm_po_num]]></var></action>', '', NULL, '', 0, NULL);

INSERT INTO `dataflow_profile` (`name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES
('Import product / supplier association', '2011-01-14 15:29:15', '2011-01-14 15:51:18', '<!-- file import -->\r\n<action type=\"dataflow/convert_adapter_io\" method=\"load\">\r\n    <var name=\"type\">file</var>\r\n    <var name=\"path\">var/import</var>\r\n    <var name=\"filename\"><![CDATA[product_supplier.csv]]></var>\r\n    <var name=\"format\"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<!-- file parser -->\r\n<action type=\"dataflow/convert_parser_csv\" method=\"parse\">\r\n    <var name=\"delimiter\"><![CDATA[;]]></var>\r\n    <var name=\"fieldnames\">true</var>\r\n    <var name=\"decimal_separator\"><![CDATA[.]]></var>\r\n    <var name=\"method\">parse</var>\r\n    <var name=\"adapter\">Purchase/Convert_Adapter_ProductSupplier</var>\r\n    <var name=\"method\">saveRow</var>\r\n</action>\r\n\r\n', '', NULL, '', 0, NULL),
('import suppliers', '2011-01-18 09:55:39', '2011-01-18 09:55:39', '<!-- file import -->\r\n<action type=\"dataflow/convert_adapter_io\" method=\"load\">\r\n    <var name=\"type\">file</var>\r\n    <var name=\"path\">var/import</var>\r\n    <var name=\"filename\"><![CDATA[suppliers.csv]]></var>\r\n    <var name=\"format\"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<!-- file parser -->\r\n<action type=\"dataflow/convert_parser_csv\" method=\"parse\">\r\n    <var name=\"delimiter\"><![CDATA[;]]></var>\r\n    <var name=\"fieldnames\">true</var>\r\n    <var name=\"decimal_separator\"><![CDATA[.]]></var>\r\n    <var name=\"method\">parse</var>\r\n    <var name=\"adapter\">Purchase/Convert_Adapter_ImportSupplier</var>\r\n    <var name=\"method\">saveRow</var>\r\n</action>\r\n', NULL, NULL, '', 0, NULL),
('Export Product / Supplier associations', '2009-10-13 06:26:39', '2009-11-12 14:21:16', '<action type=\"Purchase/convert_adapter_ExportProductSupplier\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_product_supplier.csv]]></var>    </action>', '', NULL, '', 0, NULL);

INSERT INTO `dataflow_profile` (`name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES
('Export Supply Needs', '2013-07-05 12:00:00', '2013-07-05 12:00:00', '<action type=\"Purchase/convert_adapter_supplyneeds\" method=\"save\">    <var name=\"type\">file</var>    <var name=\"path\">var/export</var>    <var name=\"filename\"><![CDATA[export_purchase_supplyneeds.csv]]></var> <var name=\"fields\"><![CDATA[product_id;stock_id;sku;name;manufacturer_id;waiting_for_delivery_qty;status;qty_min;qty_max]]></var></action>', NULL, NULL, NULL, 0, NULL);


update `dataflow_profile`
set entity_type = null
where name in ('Export Product / Supplier associations',
                'import suppliers',
                'Import product / supplier association',
                'Export Products (purchase view)',
                'Export Supply Needs',
                'Export Contact',
                'Export Suppliers',
                'Export Purchase Order Products',
                'Export Purchase Order',
                'Export Products Stock Movements',
                'Import product / warehouse stock levels', 
                'Import product barcodes', 
                'Export sales history', 
                'Export Order To Prepare Items',
                'Export Order To Prepare Pending',
                'Export Order To Prepare'
                );
                
                