<div class="entry-edit-head"> 
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('History'); ?></h4>
</div>
<fieldset id="my-fieldset">
<?php
    $collection = $this->getRsrHistory();
    foreach($collection as $item){
        ?>
        <ul class="note-list">
            <li>
                <strong><?php echo $item->getrsrh_date(); ?></strong><span class="separator">|</span>
                <strong><?php echo $this->__($item->getrsrh_description()); ?></strong>
            </li>
	</ul>
	<?php
    }
    ?>
</fieldset>