<?php
//Added for restrict country feature - Mohin, 25 Oct 2015
$nonShippableProducts = Mage::helper('restrictcountry')->getNonShippableProducts();
?>
<?php 
//Check if there is non shippable products  - Mohin, 25 Oct 2015
if(count($nonShippableProducts)>0) {
?>
<div class="restricted-products">
    <div class="error-msg items-remove">
        <p><strong><?php echo $this->__('Warning!') ?></strong></p>
        <p><?php echo $this->__('The following items are not available for shipment to your country and will be remove from your cart!') ?></p>
    </div>
    <table class="data-table" style="overflow-x:auto;">
        <thead>
            <tr>
                <th><?php echo $this->__('Name') ?></th>
                <th><?php echo $this->__('Sku') ?></th>
                <th><?php echo $this->__('Price') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($nonShippableProducts as $product){ ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($product->getName()) ?>
                </td>
                <td>
                    <?php echo $this->escapeHtml($product->getSku()) ?>
                </td>
                <td>
                    <?php echo $this->helper('core')->formatPrice($product->getFinalPrice()) ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>
<!--Original Code-->
<?php if (!$this->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>