<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<?php $card = $this->getCard() ?>

<div class="gift-card-info">
    <?php if ($card->getId()): ?>
        <div class="gift-card-info__item">
            <span class="gift-card-info__title"><?php echo $this->__("Gift Card:"); ?></span>
            <span class="gift-card-info__value"><?php echo $this->__("%s", $card->getCode()); ?></span>
        </div>

        <div class="gift-card-info__item">
            <span class="gift-card-info__title"><?php echo $this->__("Current Balance:"); ?></span>
            <span class="gift-card-info__value"><?php echo $this->__("%s", Mage::helper('core')->currency($card->getBalance())); ?></span>
        </div>

        <?php if ($card->getDateExpires()): ?>
            <div class="gift-card-info__item">
                <span class="gift-card-info__title"><?php echo $this->__("Expires:"); ?></span>
                <span class="gift-card-info__value"><?php echo $this->__("%s", $this->formatDate($card->getDateExpires(), 'short')); ?></span>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="gift-card-info__item">
            <ul class="messages gift-card-messages"><li class="error-msg"><ul><li><?php echo $this->__('Wrong or expired Gift Card Code.'); ?></li></ul></li></ul>
        </div>
    <?php endif; ?>
</div>
