<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Options */
?>

<?php $options = $this->getOptionList(); ?>

<?php if ($options): ?>
    <?php foreach ($options as $option): ?>
        <p class="product-card__option">
            <strong><?php echo $this->escapeHtml($option['label']) ?>:</strong>

            <?php if (is_array($option['value'])): ?>
                <?php echo nl2br(implode("\n", $option['value'])) ?>
            <?php else: ?>
                <?php echo $option['value'] ?>
            <?php endif; ?>
        </p>
    <?php endforeach; ?>
<?php endif ?>
