<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="wishlist">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form class="form" action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
        <?php echo $this->getBlockHtml('formkey')?>

        <p class="form__field">
            <label class="form__label form__label--required" for="email_address"><?php echo $this->__('Email addresses, separated by commas') ?></label>

            <textarea class="form__textfield textfield textfield--textarea validate-emails required-entry" name="emails" cols="60" rows="3" id="email_address"><?php echo $this->getEnteredData('emails') ?></textarea>
        </p><!-- .form__field -->

        <p class="form__field">
            <label class="form__label" for="message"><?php echo $this->__('Message') ?></label>

            <textarea class="form__textfield textfield textfield--textarea" name="message" cols="60" rows="5" id="message"><?php echo $this->getEnteredData('message') ?></textarea>
        </p><!-- .form__field -->

        <p class="form__field form__required-hint">
            <?php echo $this->__('Required Fields') ?>
        </p>

        <p class="form__field">
            <button class="button" type="submit" title="<?php echo $this->__('Share Wishlist') ?>"><?php echo $this->__('Share Wishlist') ?></button>
        </p>
    </form>

    <script>
        Validation.addAllThese([
            ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
                if (Validation.get('IsEmpty').test(v)) {
                    return true;
                }

                var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
                var emails = v.split(',');

                for (var i=0; i<emails.length; i++) {
                    if (!valid_regexp.test(emails[i].strip())) {
                        return false;
                    }
                }

                return true;
            }]
        ]);

        var dataForm = new VarienForm('form-validate', true);
    </script>
</div>
