<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="login panel__container" data-title="<?php echo $this->__('Customer Login') ?>">

    <form class="form" id="user_login_form" action="<?php echo $this->helper('aw_mobile3/url')->getCustomerPostActionUrl() ?>" method="post">

        <?php echo $this->getMessagesBlock()->addMessages(Mage::getSingleton('customer/session')->getMessages(true))->getGroupedHtml() ?>

        <?php echo $this->getBlockHtml('formkey'); ?>

        <p class="form__field">
            <label class="form__label form__label--required" for="email"><?php echo $this->__('Email Address') ?></label>
            <input class="form__textfield textfield validate-email required-entry" type="email" name="login[username]" id="email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>">
        </p><!-- .form__field -->

        <p class="form__field">
            <label class="form__label form__label--required" for="pass"><?php echo $this->__('Password') ?></label>
            <input class="form__textfield textfield validate-password required-entry" type="password" name="login[password]" id="pass">
        </p><!-- .form__field -->

        <?php echo $this->getChildHtml('form.additional.info'); ?>

        <p class="form__field">
            <button class="form__submit button" type="submit"><?php echo $this->__('Login') ?></button>
        </p><!-- .form__field -->

        <p class="form__field">
            <button class="button button--invert" data-open-container="register"><?php echo $this->__('Create an Account') ?></button>
        </p><!-- .form__field -->

        <p class="form__field login__forgot">
            <a data-open-container="forgot-password"><?php echo $this->__('Forgot Your Password?') ?></a>
        </p><!-- .form__field -->

    </form>

    <div class="panel__container-shadow"></div>
</div><!-- .panel__container -->
