<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>

<div class="cart-giftcard">
    <div id="giftcard_balance_lookup"></div>

    <form class="form" id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
        <p class="form__field">
            <label class="form__label"><?php echo $this->__("Enter the gift card code")?></label>
            <input type="text" class="required-entry discount__textfield textfield" id="giftcard_code" name="giftcard_code" value="">
        </p>
        <p class="form__field">
            <button class="form__submit button button--alternative-color" onclick="window.giftcardForm.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><?php echo $this->__('Add Gift Card') ?></button>
        </p>
        <p class="form__field">
            <button class="form__submit button button--alternative-color-invert check-gc-status" onclick="window.checkGiftCardStatus();" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><?php echo $this->__('Check Gift Card status and balance') ?></button>
        </p>
    </form>

    <script>
        window.giftcardForm = new VarienForm('giftcard-form');
        window.checkGiftCardStatus = function() {
            if (window.giftcardForm.validator && !window.giftcardForm.validator.validate()) {
                return false;
            }
            new Ajax.Updater(
                'giftcard_balance_lookup',
                '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
                {
                    onCreate: function() {
                        awMobile3.loader.show();
                    },
                    onComplete: function() {
                        awMobile3.loader.hide();
                    },
                    parameters : {giftcard_code : $('giftcard_code').value}
                }
            );
        }
    </script>
</div>
