<?php if (!$this->hasReportData()): ?>
    <p align="center" style='font-family: "Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif; font-size: 18px; margin-top: 10px; margin-bottom: 20px;'><?php echo $this->__($this->getReport()->getName()); ?></p>
    <p><?php echo $this->__('No data available'); ?></p>
<?php else: ?>
    <div id="report_<?php echo $this->getReport()->getId(); ?>" style="<?php echo $this->getContainerStyle(); ?>">
    </div>
<?php endif; ?>

<?php if ($this->hasReportData()): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function() {
            jQuery('#report_<?php echo $this->getReport()->getId(); ?>').highcharts({
                credits: { enabled: false },
                title:{ text:'<?php echo $this->__($this->getReport()->getName()); ?>'},
                subtitle: {
                    text: '<?php echo $this->getSubtitle(); ?>'
                },
                xAxis: {
                    categories: <?php echo json_encode($this->getCategories()); ?>        },
                yAxis: {
                    min: 0,
                    title: {
                        text: '<?php echo $this->getYLabel(); ?>'
                    }
                },
                legend: {
                    reversed: true
                },
                series: <?php echo json_encode($this->getReportDatas()); ?>,
                plotOptions: {
                    series: {
                        point: {
                            events: {
                                click: function () {
                                    <?php echo $this->onClick(); ?>
                                }
                            }
                        }
                    }
                },
                exporting: {
                    buttons: {
                        contextButton: {
                            menuItems: [{
                                text: 'Excel Export',
                                onclick: function () {
                                    <?php echo $this->exportJs(); ?>
                                }
                            }]
                        }
                    }
                }
            });
        });
    </script>
<?php endif; ?>