<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_product = $this->getProduct() ?>
<?php $_associatedProducts = $this->getAssociatedProducts() ?>

<p class="product-card__availability product-card__availability--grouped">
    <?php echo $this->__('Availability:') ?>

    <?php if ($_product->isSaleable() && count($_associatedProducts)): ?>
        <?php echo $this->__('In stock') ?>
    <?php else: ?>
        <?php echo $this->__('Out of stock') ?>
    <?php endif ?>
</p>

<?php echo $this->getChildHtml('product_type_data_extra') ?>

<table class="grouped-items-table">
    <thead>
        <tr>
            <th class="grouped-items-table__heading">
                <?php echo $this->__('Product Name') ?>
            </th>
            <th class="grouped-items-table__heading">
                <?php echo $this->__('Price') ?>
            </th>
            <?php if ($_product->isSaleable()): ?>
                <th class="grouped-items-table__heading grouped-items-table__qty-wrapper">
                    <?php echo $this->__('Qty') ?>
                </th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php if (count($_associatedProducts)): ?>
            <?php foreach ($_associatedProducts as $_item): ?>
                <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>

                <tr>
                    <td class="grouped-items-table__cell">
                        <?php echo $this->htmlEscape($_item->getName()) ?>
                    </td>
                    <td class="grouped-items-table__cell">
                        <?php echo $this->getPriceHtml($_item, true) ?>
                            <?php echo $this->getTierPriceHtml($_item) ?>
                    </td>
                    <?php if ($_product->isSaleable()): ?>
                        <td class="grouped-items-table__qty-wrapper grouped-items-table__cell">
                            <?php if ($_item->isSaleable()) : ?>
                                <input type="tel" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="textfield grouped-items-table__qty">
                            <?php else: ?>
                                <?php echo $this->__('Out of stock') ?>
                            <?php endif ?>
                        </td>
                    <?php endif ?>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td class="grouped-items-table__cell" colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif ?>">
                    <?php echo $this->__('No options of this product are available.') ?>
                </td>
            </tr>
        <?php endif ?>
    </tbody>
</table>
