<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $_product = $this->getProduct();
    $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
?>

<?php if (version_compare(Mage::getVersion(), '1.7.0', '>=') && $this->helper('wishlist')->isAllow()): ?>
    <?php if ($_product->getHasOptions() && !$this->getLinkToProcess()): ?>
        <button class="button js-open-panel" data-open-panel="add-to-cart-options" type="button">
            <?php echo $this->__('Configure and Add to Wishlist'); ?>
        </button>
    <?php else: ?>
        <a class="button" href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;">
            <?php echo $this->__('Add to Wishlist') ?>
        </a>
    <?php endif; ?>
<?php endif; ?>
