<h1 class="page-heading"><?php echo $this->__('Access denied or nothing to configure') ?></h1>
<p>
<?php echo $this->__('This error is usually caused by enabling an extension while still being logged into the admin area. <u>Please try to logout and sign in again</u>. If that does not work, this error may also be caused by there being nothing to configure in this configuration scope.') ?><br/>
</p>
