<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="discount panel panel--from-bottom">
    <div class="panel__inner">

        <div class="panel__header">
            <button class="panel__back panel__action"></button>
            <h2 class="panel__title"><span class="panel__title-text"><?php echo $this->__("Discounts") ?></span></h2>
            <button class="panel__close panel__action"><svg class="panel__action-icon panel__action-icon--close svg-icon"><use xlink:href="#icon-close" /></svg><span class="hide"><?php echo $this->__("Close") ?></span></button>
        </div>

        <div class="panel__content">
            <div class="discount__container panel__container">

                <form class="form" id="discount-coupon-form" action="<?php echo $this->helper('aw_mobile3/url')->getCartCouponPostUrl() ?>" method="post">

                    <input type="hidden" name="remove" id="remove-coupon" value="0">

                    <p class="form__field">
                        <label class="form__label" for="coupon_code"><?php echo $this->__("Coupon Code")?></label>

                        <input class="form__textfield textfield" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>">
                    </p>

                    <p class="form__field">
                        <button class="discount__submit button" type="submit"><?php echo $this->__('Apply Coupon') ?></button>
                    </p>
                    <?php if (strlen($this->getCouponCode())): ?>
                        <p class="form__field">
                            <button class="discount__submit js-remove-discount button button--invert" type="button"><?php echo $this->__('Cancel Coupon') ?></button>
                        </p>
                    <?php endif; ?>
                </form>

                <?php  echo $this->getChildHtml('giftcards')  ?>

                <div class="panel__container-shadow"></div>
            </div><!-- .panel__container -->
        </div><!-- .panel__content -->

    </div>
</div>