<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><!DOCTYPE html>
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
    <?php echo $this->getChildHtml('load_icons') ?>
</head>
<body>

<?php echo $this->getChildHtml('after_body_start') ?>

<header class="header">
    <div class="header__inner">
        <div class="site-header">

            <?php echo $this->getChildHtml('header') ?>

        </div><!-- .site-header -->

        <div class="page-header">
            <?php echo $this->getChildHtml('page_header') ?>
            <?php /*echo $this->getChildHtml('breadcrumbs')*/ ?>
        </div><!-- .page-header -->

    </div><!-- .header__inner -->
</header>

<div class="wrapper">
    <div class="container">

        <?php $global_messages = trim($this->getChildHtml('global_messages')); ?>
        <?php if ($global_messages != ''): ?>
            <div class="global-messages">
                <?php echo $global_messages ?>
            </div>
        <?php endif; ?>

        <?php echo $this->getChildHtml('content') ?>
    </div><!-- .container -->

    <footer class="footer">
        <?php echo $this->getChildHtml('footer') ?>
    </footer><!-- .footer -->
</div><!-- .wrapper -->

<?php echo $this->getChildHtml('topMenu') ?>

<?php echo $this->getChildHtml('topSearch') ?>

<?php echo $this->getChildHtml('customer_account') ?>

<?php echo $this->getChildHtml('panels') ?>

<?php echo $this->getChildHtml('loaders') ?>

<?php echo $this->getChildHtml('before_body_end') ?>

</body>
</html>
