<?php if ($this->getMethod()->getWiretransferInstructions()): ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="input-box">

            <?php if ($this->getMethod()->getWiretransferInstructions()): ?>
               <?php
/*			   <label><?php echo Mage::helper('payment')->__('You will need to download & print the PDF in the confirmation email for wire instructions:') ?></label>
     */
?>	 <div class="checkmo-mailing-address">
                    <?php echo nl2br($this->getMethod()->getWiretransferInstructions()) ?>
                </div>
            <?php endif; ?>
        </div>
    </li>
</ul>
<?php endif; ?>
