<?php $_data = $this->getFormData(); ?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Create an account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <p><?php echo $this->__('You must create an account in order to request a product return.'); ?></p>

            <form action="<?php echo $this->getUrl('*/*/Submit') ?>" method="post" id="form-validate">
                <input type="hidden" name="order_id" value="<?php echo $this->getOrder()->getId(); ?>">
                <div class="content">
                    <ul class="form-list">
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                        </li>
                        <li>
                            <label for="email_address"
                                   class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                            </label>

                            <div class="input-box">
                                <input type="text" name="email" id="email_address"
                                       value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>"
                                       title="<?php echo $this->__('Email Address') ?>"
                                       class="input-text validate-email required-entry"/>
                            </div>
                        </li>
                        <?php if ($this->isNewsletterEnabled()): ?>
                            <li class="control">
                                <div class="input-box">
                                    <input type="checkbox" name="is_subscribed"
                                           title="<?php echo $this->__('Sign Up for our Newsletter') ?>" value="1"
                                           id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                           class="checkbox"/>
                                </div>
                                <label for="is_subscribed"><?php echo $this->__('Sign Up for our Newsletter') ?></label>
                            </li>
                        <?php endif ?>
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                        <?php endif ?>
                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                        <?php endif ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                        <?php endif ?>
                        <li class="fields">
                            <div class="field">
                                <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?>
                                </label>

                                <div class="input-box">
                                    <input type="password" name="password" id="password"
                                           title="<?php echo $this->__('Password') ?>"
                                           class="input-text required-entry validate-password"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="confirmation"
                                       class="required"><em>*</em><?php echo $this->__('Confirm Password') ?>
                                </label>

                                <div class="input-box">
                                    <input type="password" name="confirmation"
                                           title="<?php echo $this->__('Confirm Password') ?>"
                                           id="confirmation" class="input-text required-entry validate-cpassword"/>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <p class="required" style="margin:0;"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="buttons-set">
                    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"
                                            class="back-link">
                            <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                    <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button">
                        <span><span><?php echo $this->__('Submit') ?></span></span></button>
                </div>
            </form>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        var dataLoginForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>